# Generated by Django 4.2.3 on 2023-07-15 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fotodb', '0002_category_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
