# Generated by Django 4.2.3 on 2023-07-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotodb', '0005_tag_like_image_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='tags',
        ),
        migrations.AddField(
            model_name='image',
            name='tags',
            field=models.CharField(blank=True, choices=[('nature', 'Nature'), ('food', 'Food'), ('travel', 'Travel'), ('art', 'Art'), ('music', 'Music')], max_length=255),
        ),
    ]
