# Generated by Django 4.2.3 on 2023-07-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotodb', '0007_remove_image_tags_image_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='fotodb.tag'),
        ),
    ]
