# Generated by Django 4.2.3 on 2023-07-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotodb', '0008_alter_image_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
