# Generated by Django 4.2.3 on 2023-07-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotodb', '0009_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='tags',
            field=models.ManyToManyField(blank=True, to='fotodb.tag'),
        ),
    ]
